In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
data=pd.read_csv('/kaggle/input/breast-cancer-dataset/breast-cancer.csv')
data

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [3]:
data.isnull().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [4]:
data.nunique()

id                         569
diagnosis                    2
radius_mean                456
texture_mean               479
perimeter_mean             522
area_mean                  539
smoothness_mean            474
compactness_mean           537
concavity_mean             537
concave points_mean        542
symmetry_mean              432
fractal_dimension_mean     499
radius_se                  540
texture_se                 519
perimeter_se               533
area_se                    528
smoothness_se              547
compactness_se             541
concavity_se               533
concave points_se          507
symmetry_se                498
fractal_dimension_se       545
radius_worst               457
texture_worst              511
perimeter_worst            514
area_worst                 544
smoothness_worst           411
compactness_worst          529
concavity_worst            539
concave points_worst       492
symmetry_worst             500
fractal_dimension_worst    535
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [6]:
data['diagnosis']=le.fit_transform(data['diagnosis'])
data

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,1,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,1,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,1,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,1,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,0,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [7]:
from sklearn.feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=0.3)

In [8]:
data['diagnosis'].value_counts()

diagnosis
0    357
1    212
Name: count, dtype: int64

In [9]:
x=data.drop('diagnosis',axis=1)
y=data['diagnosis']

In [10]:
from scipy.stats import pearsonr
corr1=pearsonr(x['radius_mean'],y)
corr2=pearsonr(x['texture_mean'],y)
corr1,corr2

(PearsonRResult(statistic=0.7300285113754564, pvalue=8.465940572262422e-96),
 PearsonRResult(statistic=0.4151852998452044, pvalue=4.0586360478983284e-25))

In [11]:
columns=x.columns
for i in columns:
    corr=pearsonr(x[i],y)
    print(i)
    print(corr)

id
PearsonRResult(statistic=0.03976850962171704, pvalue=0.34368185775951193)
radius_mean
PearsonRResult(statistic=0.7300285113754564, pvalue=8.465940572262422e-96)
texture_mean
PearsonRResult(statistic=0.4151852998452044, pvalue=4.0586360478983284e-25)
perimeter_mean
PearsonRResult(statistic=0.7426355297258329, pvalue=8.43625103617469e-101)
area_mean
PearsonRResult(statistic=0.7089838365853898, pvalue=4.734564310308251e-88)
smoothness_mean
PearsonRResult(statistic=0.358559965085932, pvalue=1.0518503592032461e-18)
compactness_mean
PearsonRResult(statistic=0.5965336775082531, pvalue=3.9382631058875453e-56)
concavity_mean
PearsonRResult(statistic=0.6963597071719059, pvalue=9.96655575507189e-84)
concave points_mean
PearsonRResult(statistic=0.7766138400204355, pvalue=7.101150161056389e-116)
symmetry_mean
PearsonRResult(statistic=0.33049855426254715, pvalue=5.733384028466726e-16)
fractal_dimension_mean
PearsonRResult(statistic=-0.012837602698432404, pvalue=0.7599368037256309)
radius_se
PearsonRResult(statistic=0.5671338208247177, pvalue=9.738948656461524e-50)
texture_se
PearsonRResult(statistic=-0.008303332973877435, pvalue=0.8433320287670161)
perimeter_se
PearsonRResult(statistic=0.5561407034314831, pvalue=1.6519051758498198e-47)
area_se
PearsonRResult(statistic=0.5482359402780244, pvalue=5.8955213926059086e-46)
smoothness_se
PearsonRResult(statistic=-0.06701601057948735, pvalue=0.11029660865789263)
compactness_se
PearsonRResult(statistic=0.2929992442488583, pvalue=9.975994654075077e-13)
concavity_se
PearsonRResult(statistic=0.2537297659808304, pvalue=8.260176167970008e-10)
concave points_se
PearsonRResult(statistic=0.40804233271650464, pvalue=3.072308768818184e-24)
symmetry_se
PearsonRResult(statistic=-0.006521755870647961, pvalue=0.876641818385877)
fractal_dimension_se
PearsonRResult(statistic=0.07797241739025615, pvalue=0.0630735508223939)
radius_worst
PearsonRResult(statistic=0.7764537785950396, pvalue=8.482291921684506e-116)
texture_worst
PearsonRResult(statistic=0.4569028213967983, pvalue=1.0780574879493332e-30)
perimeter_worst
PearsonRResult(statistic=0.7829141371737592, pvalue=5.771397139669152e-119)
area_worst
PearsonRResult(statistic=0.7338250349210509, pvalue=2.8288477042871667e-97)
smoothness_worst
PearsonRResult(statistic=0.4214648610664027, pvalue=6.575143633984149e-26)
compactness_worst
PearsonRResult(statistic=0.590998237841792, pvalue=7.069816352538606e-55)
concavity_worst
PearsonRResult(statistic=0.659610210369233, pvalue=2.464663956783045e-72)
concave points_worst
PearsonRResult(statistic=0.7935660171412698, pvalue=1.9690997072166206e-124)
symmetry_worst
PearsonRResult(statistic=0.41629431104861914, pvalue=2.9511205771539195e-25)
fractal_dimension_worst
PearsonRResult(statistic=0.3238721887208239, pvalue=2.316432449982792e-15)

In [12]:
from sklearn.feature_selection import chi2
chi2=chi2(x,y)
chi2

(array([4.62294838e+08, 2.66104917e+02, 9.38975081e+01, 2.01110286e+03,
        5.39916559e+04, 1.49899264e-01, 5.40307549e+00, 1.97123536e+01,
        1.05440354e+01, 2.57379775e-01, 7.43065536e-05, 3.46752472e+01,
        9.79353970e-03, 2.50571896e+02, 8.75850471e+03, 3.26620664e-03,
        6.13785332e-01, 1.04471761e+00, 3.05231563e-01, 8.03633831e-05,
        6.37136566e-03, 4.91689157e+02, 1.74449400e+02, 3.66503542e+03,
        1.12598432e+05, 3.97365694e-01, 1.93149220e+01, 3.95169151e+01,
        1.34854195e+01, 1.29886140e+00, 2.31522407e-01]),
 array([0.00000000e+000, 8.01397628e-060, 3.32292194e-022, 0.00000000e+000,
        0.00000000e+000, 6.98631644e-001, 2.01012999e-002, 9.00175712e-006,
        1.16563638e-003, 6.11926026e-001, 9.93122221e-001, 3.89553429e-009,
        9.21168192e-001, 1.94877489e-056, 0.00000000e+000, 9.54425121e-001,
        4.33366115e-001, 3.06726812e-001, 5.80621137e-001, 9.92847410e-001,
        9.36379753e-001, 6.11324751e-109, 7.89668299e-040, 0.00000000e+000,
        0.00000000e+000, 5.28452867e-001, 1.10836762e-005, 3.25230064e-010,
        2.40424384e-004, 2.54421307e-001, 6.30397277e-001]))

In [13]:
from sklearn.feature_selection import f_classif
F_values, p_values = f_classif(x, y)
F_values,p_values

(array([8.98150436e-01, 6.46981021e+02, 1.18096059e+02, 6.97235272e+02,
        5.73060747e+02, 8.36511234e+01, 3.13233079e+02, 5.33793126e+02,
        8.61676020e+02, 6.95274435e+01, 9.34592949e-02, 2.68840327e+02,
        3.90947023e-02, 2.53897392e+02, 2.43651586e+02, 2.55796780e+00,
        5.32473391e+01, 3.90144816e+01, 1.13262760e+02, 2.41174067e-02,
        3.46827476e+00, 8.60781707e+02, 1.49596905e+02, 8.97944219e+02,
        6.61600206e+02, 1.22472880e+02, 3.04341063e+02, 4.36691939e+02,
        9.64385393e+02, 1.18860232e+02, 6.64439606e+01]),
 array([3.43681858e-001, 8.46594057e-096, 4.05863605e-025, 8.43625104e-101,
        4.73456431e-088, 1.05185036e-018, 3.93826311e-056, 9.96655576e-084,
        7.10115016e-116, 5.73338403e-016, 7.59936804e-001, 9.73894866e-050,
        8.43332029e-001, 1.65190518e-047, 5.89552139e-046, 1.10296609e-001,
        9.97599465e-013, 8.26017617e-010, 3.07230877e-024, 8.76641818e-001,
        6.30735508e-002, 8.48229192e-116, 1.07805749e-030, 5.77139714e-119,
        2.82884770e-097, 6.57514363e-026, 7.06981635e-055, 2.46466396e-072,
        1.96909971e-124, 2.95112058e-025, 2.31643245e-015]))

In [14]:
from sklearn.feature_selection import mutual_info_classif
X_selected = mutual_info_classif(x, y)
X_selected

array([0.10652203, 0.36360615, 0.09784391, 0.40471539, 0.35763037,
       0.08120947, 0.21515924, 0.37356478, 0.44119501, 0.06535491,
       0.00396861, 0.24803092, 0.00168275, 0.27588716, 0.3408883 ,
       0.01481078, 0.07626464, 0.11716886, 0.12677778, 0.01347923,
       0.03986719, 0.45166529, 0.1192816 , 0.47638893, 0.4632881 ,
       0.09575776, 0.22666674, 0.31605444, 0.43757518, 0.09419246,
       0.0683802 ])

In [15]:
columns

Index(['id', 'radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean',
       'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [16]:
drop=['fractal_dimension_mean','texture_se','symmetry_se']
x1=x.drop(drop,axis=1)

In [17]:
x1

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
def forward_selection(a, b, model, max_features=None):
    selected_features = []
    remaining_features = list(a.columns)
    best_score = 0.0
    if max_features is None:
        max_features = len(remaining_features)
    for i in range(max_features):
        scores_with_candidates = []
        for feature in remaining_features:
            current_features = selected_features + [feature]
            X_train, X_test, y_train, y_test = train_test_split(a[current_features], y, test_size=0.2, random_state=42)
            model.fit(X_train, y_train)
            y_pred = model.predict(X_test)
            score = accuracy_score(y_test, y_pred)
            scores_with_candidates.append((score, feature))
        scores_with_candidates.sort(reverse=True)
        best_new_score, best_new_feature = scores_with_candidates[0]
        if best_new_score > best_score:
            best_score = best_new_score
            selected_features.append(best_new_feature)
            remaining_features.remove(best_new_feature)
            print(f"Selected: {best_new_feature}, Accuracy: {best_new_score:.4f}")
        else:
            break
    
    return selected_features
model = LogisticRegression(solver='liblinear', multi_class='ovr')
selected_features = forward_selection(x1, y, model)
print("Final selected features:", selected_features)

Selected: radius_worst, Accuracy: 0.9474
Selected: perimeter_se, Accuracy: 0.9561
Selected: compactness_worst, Accuracy: 0.9649
Final selected features: ['radius_worst', 'perimeter_se', 'compactness_worst']

In [19]:
x2=x1[['radius_worst', 'perimeter_se', 'compactness_worst']]
x2

     radius_worst  perimeter_se  compactness_worst
0          25.380         8.589            0.66560
1          24.990         3.398            0.18660
2          23.570         4.585            0.42450
3          14.910         3.445            0.86630
4          22.540         5.438            0.20500
..            ...           ...                ...
564        25.450         7.673            0.21130
565        23.690         5.203            0.19220
566        18.980         3.425            0.30940
567        25.740         5.772            0.86810
568         9.456         2.548            0.06444

[569 rows x 3 columns]

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x2,y,test_size=0.25)
model.fit(x_train,y_train)

LogisticRegression(multi_class='ovr', solver='liblinear')

In [21]:
y_tests=[]
for i in y_test:
    y_tests.append(i)
np.array(y_tests)

array([1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0])

In [22]:
y_preds=model.predict(x_test)
accuracy_score(y_test,y_preds)

0.916083916083916