In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import sklearn
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.preprocessing import LabelEncoder

In [2]:
data=pd.read_csv('/kaggle/input/predict-people-personality-types/data.csv')
data=pd.DataFrame(data)
data.head()

,Age,Gender,Education,Introversion Score,Sensing Score,Thinking Score,Judging Score,Interest,Personality
0,19.0,Male,0,9.47080,7.141434,6.03696,4.360278,Unknown,ENFP
1,27.0,Female,0,5.85392,6.160195,0.80552,4.221421,Sports,ESFP
2,21.0,Female,0,7.08615,3.388433,2.66188,5.127320,Unknown,ENFP
3,28.0,Male,0,2.01892,4.823624,7.30625,5.986550,Others,INTP
4,36.0,Female,1,9.91703,4.755080,5.31469,4.677213,Technology,ENFP

In [3]:
le=LabelEncoder()
data['Gender']=data['Gender'].map({'Male':1,'Female':0,})
data['Interest']=data['Interest'].map({'Unknown':0, 'Sports':1, 'Others':2, 'Technology':3, 'Arts':4})
data['personality']=le.fit_transform(data['Personality'])

In [4]:
data2=data.drop('Personality',axis=1)
data2

,Age,Gender,Education,Introversion Score,Sensing Score,Thinking Score,Judging Score,Interest,personality
0,19.0,1,0,9.47080,7.141434,6.03696,4.360278,0,1
1,27.0,0,0,5.85392,6.160195,0.80552,4.221421,1,5
2,21.0,0,0,7.08615,3.388433,2.66188,5.127320,0,1
3,28.0,1,0,2.01892,4.823624,7.30625,5.986550,2,11
4,36.0,0,1,9.91703,4.755080,5.31469,4.677213,3,1
...,...,...,...,...,...,...,...,...,...
128056,27.0,1,0,5.11456,7.764336,5.72341,2.686904,4,7
128057,19.0,1,0,3.00078,2.525392,4.71081,3.657814,0,9
128058,26.0,0,1,8.16219,3.433857,2.45531,5.541144,4,1
128059,24.0,1,0,9.37782,5.077443,1.79598,6.762643,0,0
128060,27.0,1,0,7.78827,4.770737,3.18600,6.204355,2,0

In [5]:
data2.isnull().sum()

Age                   0
Gender                0
Education             0
Introversion Score    0
Sensing Score         0
Thinking Score        0
Judging Score         0
Interest              0
personality           0
dtype: int64

In [6]:
data2.describe

<bound method NDFrame.describe of          Age  Gender  Education  Introversion Score  Sensing Score  \
0       19.0       1          0             9.47080       7.141434
1       27.0       0          0             5.85392       6.160195
2       21.0       0          0             7.08615       3.388433
3       28.0       1          0             2.01892       4.823624
4       36.0       0          1             9.91703       4.755080
...      ...     ...        ...                 ...            ...
128056  27.0       1          0             5.11456       7.764336
128057  19.0       1          0             3.00078       2.525392
128058  26.0       0          1             8.16219       3.433857
128059  24.0       1          0             9.37782       5.077443
128060  27.0       1          0             7.78827       4.770737

        Thinking Score  Judging Score  Interest  personality
0              6.03696       4.360278         0            1
1              0.80552       4.221421         1            5
2              2.66188       5.127320         0            1
3              7.30625       5.986550         2           11
4              5.31469       4.677213         3            1
...                ...            ...       ...          ...
128056         5.72341       2.686904         4            7
128057         4.71081       3.657814         0            9
128058         2.45531       5.541144         4            1
128059         1.79598       6.762643         0            0
128060         3.18600       6.204355         2            0

[128061 rows x 9 columns]>

In [7]:
data2.shape

(128061, 9)

In [8]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [9]:
from sklearn.model_selection import train_test_split
x=data2.drop('Thinking Score',axis=1)
y=data2['Thinking Score']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=49)

In [10]:
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [11]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [12]:
model.fit(x_train,y_train)

LinearRegression()

In [13]:
y_pred=model.predict(x_test)

In [14]:
y_pred

array([4.57675427, 5.12918997, 5.46509554, ..., 2.80956015, 2.82179702,
       4.95602215])

In [15]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_pred)

2.321301371539041

In [16]:
model.score(x_train,y_train)

0.09679025143894582

In [17]:
from sklearn.linear_model import Ridge
model2=Ridge(alpha=2)
model2.fit(x_train,y_train)
y_pred2=model2.predict(x_test)

In [18]:
model2.score(x_train,y_train)
mean_absolute_error(y_pred2,y_test)

2.321307675544995

In [19]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly = PolynomialFeatures(degree=2) 
X_poly = poly.fit_transform(x_train)

model3 = LinearRegression()
model3.fit(X_poly, y_train)
y_pred3 = model3.predict(poly.transform(x_test))

In [20]:
mean_absolute_error(y_test,y_pred3)

26705807820.725906

In [21]:
y_pred3

array([-2.03189868e+10,  3.35992948e+10,  2.35159990e+10, ...,
       -3.04022827e+10, -2.03189868e+10, -3.04022827e+10])

In [22]:
from sklearn.neighbors import KNeighborsRegressor

model5 = KNeighborsRegressor(n_neighbors=2)
model5.fit(x_train, y_train)
y_pred5 = model5.predict(x_test)

In [23]:
model5.score(x_train,y_train)

0.8169761487436268

In [24]:
mean_absolute_error(y_test,y_pred5)

1.7277224734507748

In [25]:
import pickle
import os
path='C:/Users/yaswa/OneDrive/Desktop/Datascience/Trained Models'
os.makedirs(os.path.dirname(path), exist_ok=True)
with open (path,'wb') as file:
    pickle.dump(data2,file)